spring:
  application:
    name: LoginRegAPI
  datasource:
    url: jdbc:mysql://localhost:3306/dms
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  logging:
    level:
      org:
        hibernate:
          sql: debug

jwt:
  secret: oWxiA4J+s34cHVbcwhYIcN5P0xq9CjYAkUz/ai3Wh8Q=
  expiration: 3600000

endpoints:
  register: /api/register
  login: /api/login
  welcome: /api/welcome

storage: C:\Users\hassa\OneDrive\Desktop\Db\
